name: Deploy to Azure (Service Principal - Legacy)

on:
  push:
    branches:
      - main
      - new-main
  workflow_dispatch:

permissions:
  contents: read

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_APP_NAME }}
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Install with PRISMA_SKIP_POSTINSTALL to prevent client generation
          npm install
        env:
          PRISMA_SKIP_POSTINSTALL: "true"

      - name: Create production env file
        run: |
          cat > .env.production << EOL
          # Production environment variables for Azure
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          NODE_ENV=production
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          PORT=8080
          SKIP_ENV_VALIDATION=true
          SKIP_ESLINT_VALIDATION=true
          SKIP_PRISMA_VALIDATION=true
          EOL

      - name: Build for Azure
        run: |
          # Run the build with standalone output
          npm run build
        env:
          NODE_ENV: production
          SKIP_ENV_VALIDATION: "true"
          PRISMA_SKIP_POSTINSTALL: "true"
      
      - name: Azure Post-Build Tasks
        run: |
          echo "Running Azure post-build tasks..."
          # Check if .next directory exists
          if [ ! -d ".next" ]; then
            echo "Error: .next directory does not exist. Build may have failed."
            exit 1
          fi
          
          # Check if standalone directory exists, create if not
          if [ ! -d ".next/standalone" ]; then
            echo "Creating missing standalone directory..."
            mkdir -p .next/standalone
          fi
          
          # CRITICAL: Remove Prisma from standalone to prevent database connection at startup
          rm -rf .next/standalone/node_modules/@prisma 2>/dev/null || true
          rm -rf .next/standalone/node_modules/prisma 2>/dev/null || true
          
          # Remove any other unnecessary modules
          rm -rf .next/standalone/node_modules/typescript 2>/dev/null || true
          rm -rf .next/standalone/node_modules/eslint 2>/dev/null || true
          
          # Copy entry point files
          cp index.js .next/standalone/
          cp server-static.js .next/standalone/
          cp server-parent.js .next/standalone/
          cp server-child.js .next/standalone/
          cp server-minimal.js .next/standalone/
          cp server-simple.js .next/standalone/
          cp test-server.js .next/standalone/
          cp web.config .next/standalone/
          
          # Copy public assets if the directory exists
          if [ -d "public" ]; then
            echo "Copying public directory..."
            cp -r public .next/standalone/
          else
            echo "Note: public directory does not exist, creating empty one."
            mkdir -p .next/standalone/public
          fi
          
          # Copy app directory assets if they exist (for images, etc.)
          if [ -d "app" ]; then
            echo "Copying app directory for assets..."
            mkdir -p .next/standalone/app
            # Only copy asset files, not code
            find app -type f -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.svg" -o -name "*.ico" -o -name "*.gif" | xargs -I{} cp --parents {} .next/standalone/
          fi
          
          # Create .next directory inside standalone if it doesn't exist
          mkdir -p .next/standalone/.next
          
          # Copy static assets if they exist
          if [ -d ".next/static" ]; then
            cp -r .next/static .next/standalone/.next/
          else
            echo "Warning: .next/static directory not found."
          fi

      # Login to Azure using Service Principal (Legacy method)
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Create a deployment package
      - name: Create deployment package
        run: |
          cd .next/standalone
          zip -r ../../deploy.zip .
          cd ../..
          
      # Deploy using Azure CLI
      - name: Deploy to Azure App Service using Azure CLI
        run: |
          echo "Starting deployment with Azure CLI..."
          
          # Deploy the ZIP file using Azure CLI
          az webapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_APP_NAME }} \
            --src deploy.zip \
            --timeout 300
          
          echo "✓ Deployment completed successfully!"
          echo "Your app should be available at: https://${{ secrets.AZURE_APP_NAME }}.azurewebsites.net"
      
      # Configure App Startup
      - name: Configure App Startup  
        run: |
          echo "Configuring app settings..."
          
          # Set startup command
          az webapp config set \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_APP_NAME }} \
            --startup-file "node index.js"
          
          # Set environment variable
          az webapp config appsettings set \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_APP_NAME }} \
            --settings NODE_ENV=production NODE_OPTIONS="--max-old-space-size=256 --no-warnings"
          
          echo "✓ App configured!"
          
      # Logout from Azure
      - name: Logout from Azure
        run: az logout
        if: always()
