# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - PRYYSM-V2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          npx prisma generate
          npm run build --if-present
          npm run test --if-present
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NODE_ENV: production

      - name: Verify build output
        run: |
          echo "🔍 Verifying .next folder..."
          ls -la .next/ || echo "❌ ERROR: .next folder not found!"
          echo ""
          echo "📊 Artifact contents:"
          du -sh .next/ package.json public/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .next
            node_modules
            public
            prisma
            package.json
            package-lock.json
            index.js
            instrumentation.ts
            jsconfig.json
            web.config
            .deployment
            .npmrc
            Procfile
            azure-startup.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PRYYSM-V2'
          slot-name: 'Production'
          package: .

      - name: 'Set startup command'
        run: |
          # Get resource group name for the app
          RG=$(az webapp show --name PRYYSM-V2 --query resourceGroup -o tsv)
          echo "Found resource group: $RG"
          
          # Set startup command
          az webapp config appsettings set --resource-group "$RG" --name PRYYSM-V2 --settings STARTUP_COMMAND="cd /home/site/wwwroot && npm install --legacy-peer-deps --omit=dev && node node_modules/.bin/next start"
          